### ISSUE TITLE
[1.21] Missing item tags 

### ISSUE THREAD

**Issue by ffuentesm** [Ax3dGaming/EndersDelight#19]
chorus crate:
c:storage_blocks/chorus

Shulker Bowl:
farmersdelight:serving_container

c:foods:
mite crust, shulker mollusk, shulker filet, uncanny cookies, chorus pie,  stuffed shulker

c:foods/soup:
chorus stew, endermite stew

c:foods/raw_meat:
shulker mollusk, shulker filet

minecraft:meat:
shulker mollusk, shulker filet

c:foods/cookie:
uncanny cookies

c:foods/food_poisoning:
mite crust, shulker mollusk, shulker filet, uncanny cookies

**Comment by Ax3dGaming** [comment]
I will fix it today, thanks you !

**Comment by Ax3dGaming** [comment]
I post the update
